/*
=======================================================================
Magnitude Exploration
=======================================================================
Compare the measure values by categories. It helps us understand the 
importance of different categories.
    - Low Cardinality Dimension --> Dimension with few unique values
    - High Cardinality Dimension --> Dimension with many unique values

Syntax ==> SUM/AVG/COUNT [MEASURE] By [DIMENSION]

  - Find total customers by countries 
  - Find total customers by gender
  - Find total products by category
  - Find the average costs in each category
  - Find the total revenue generated for each category
  - Find total revenue is generated by each customer
  - Find the distribution of sold items across countries
=======================================================================
*/

-- Find total customers by countries
SELECT 
    country, 
    COUNT(customer_key) AS total_customers 
FROM gold.dim_customers
GROUP BY country
ORDER BY COUNT(customer_key) DESC;

-- Find total customers by gender
SELECT 
    gender, 
    COUNT(customer_key) AS total_customers 
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find total products by category
SELECT 
    category, 
    COUNT(product_key) AS total_products 
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- Find the average costs in each category
SELECT 
    category, 
    AVG(cost) AS average_cost 
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC;

-- Find the total revenue generated for each category
SELECT 
    gp.category, 
    SUM(gs.sales_amount) AS total_revenue 
FROM gold.fact_sales gs 
LEFT JOIN gold.dim_products gp 
    ON gs.product_key = gp.product_key
GROUP BY gp.category
ORDER BY total_revenue DESC;

-- Find total revenue is generated by each customer
SELECT 
    gc.customer_id,
    gc.first_name,
    gc.last_name,
    SUM(gs.sales_amount) AS total_revenue 
FROM gold.fact_sales gs 
LEFT JOIN gold.dim_customers gc 
    ON gs.customer_key = gc.customer_key
GROUP BY gc.customer_id
ORDER BY total_revenue DESC;

-- Find the distribution of sold items across countries
SELECT 
    gc.country, 
    SUM(gs.quantity) AS items_sold 
FROM gold.fact_sales gs 
LEFT JOIN gold.dim_customers gc 
    ON gs.customer_key = gc.customer_key
GROUP BY gc.country
ORDER BY items_sold DESC;
